"""Form management utilities for admin model views.

This module handles form scaffolding, generation, instantiation, and URL-aware
form setup for list and detail views.
"""

from typing import Any

from wtforms.fields import HiddenField
from wtforms.fields.core import UnboundField
from wtforms.validators import InputRequired

from ....forms.form.flask_form import FlaskForm
from ....forms.widgets import EditableWidget


class FormsMixin:
    """Mixin for form scaffolding and management in admin views."""

    base_form_class = FlaskForm
    """Base WTForms form class used for generated forms."""

    form_args: dict[str, dict[str, Any]] = {}
    """Configuration for individual form fields."""

    form_columns: list | None = None
    """List of form fields to include."""

    form_excluded_columns: list | None = None
    """List of form fields to exclude."""

    form_widget_args: dict[str, dict[str, Any]] | None = None
    """WTForms widget arguments for generated forms."""

    form_extra_fields: dict[str, Any] | None = None
    """Additional field definitions for the form."""

    form_ajax_refs: dict[str, Any] | None = None
    """AJAX-related form references."""

    _create_form_class: type | None = None
    _edit_form_class: type | None = None
    _delete_form_class: type | None = None
    _list_form_class: type | None = None
    _form_ajax_refs: dict[str, Any] = {}

    def scaffold_form(self) -> type:
        """Build a form class from the model.

        This method must be implemented by subclasses.

        Returns:
            Type: A form class for the model.

        Raises:
            NotImplementedError: If the subclass does not implement this hook.
        """
        return None

    def scaffold_list_form(self, widget=None, validators=None) -> type:
        """Build the editable list form for the index view.

        Args:
            widget: WTForms widget class. Defaults to ``EditableWidget``.
            validators: Form configuration containing only validator metadata.

        Returns:
            type: A WTForms form class.

        Raises:
            NotImplementedError: If the subclass does not implement this hook.
        """
        raise NotImplementedError("Please implement scaffold_list_form method")

    def get_list_form(self) -> type:
        """Return the editable list form for the index view.

        The method only propagates validator metadata from ``form_args`` and
        allows subclasses to override the widget used for inline editing.

        Returns:
            type: A WTForms form class.
        """
        if self.form_args:
            validators = {
                key: {"validators": value["validators"]}
                for key, value in self.form_args.items()
                if value.get("validators")
            }
        else:
            validators = None

        return self.scaffold_list_form(validators=validators)

    def create_editable_list_form(self, form_class, widget=None):
        """
        Create a form class with all the fields wrapped in a FieldList.

        Wrapping each field in FieldList allows submitting POST requests
        in this format: ('<field_name>-<primary_key>', '<value>')

        Used in the editable list view.

        Args:
            base_form_class:
                WTForms form class, by default `base_form_class` from base.
            form_class:
                WTForms form class generated by `form.get_form`.
            widget:
                WTForms widget class. Defaults to `EditableWidget`.
        """
        if widget is None:
            widget = EditableWidget()

        class ListForm(self.base_form_class):
            pk = HiddenField(validators=[InputRequired()])

        for name, obj in form_class.__dict__.items():
            if not name.startswith("_") and isinstance(obj, UnboundField):
                if name == "pk":
                    raise Exception("Form already has a pk column.")
                obj.kwargs["widget"] = widget
                setattr(ListForm, name, obj)

        return ListForm

    def get_create_form(self) -> type:
        """Return the form used by the create view.

        Subclasses can override this method to customize behavior.

        Returns:
            Type: A WTForms form class.
        """
        return self.scaffold_form()

    def get_edit_form(self) -> type:
        """Return the form used by the edit view.

        Subclasses can override this method to customize behavior.

        Returns:
            Type: A WTForms form class.
        """
        return self.scaffold_form()

    def get_delete_form(self) -> type:
        """Return the form used by the delete view.

        Subclasses can override this method to customize behavior.

        Returns:
            Type: A WTForms form class.
        """

        class DeleteForm(self.base_form_class):
            id = HiddenField(validators=[InputRequired()])

        return DeleteForm

    def create_form(self, *args, **kwargs) -> Any:
        """Instantiate the form used by the create view.

        Args:
            *args: Positional arguments forwarded to the form.
            **kwargs: Keyword arguments forwarded to the form.

        Returns:
            Any: A form instance.
        """
        return self._create_form_class(*args, **kwargs)

    def edit_form(self, *args, **kwargs) -> Any:
        """Instantiate the form used by the edit view.

        Args:
            *args: Positional arguments forwarded to the form.
            **kwargs: Keyword arguments forwarded to the form.

        Returns:
            Any: A form instance.
        """
        return self._edit_form_class(*args, **kwargs)

    def delete_form(self, *args, **kwargs) -> Any:
        """Instantiate the form used by the delete view.

        Args:
            *args: Positional arguments forwarded to the form.
            **kwargs: Keyword arguments forwarded to the form.

        Returns:
            Any: A form instance.
        """
        return self._delete_form_class(*args, **kwargs)

    def list_form(self, *args, **kwargs) -> Any:
        """Instantiate and return the list-edit form for the index view.

        Args:
            *args: Positional arguments forwarded to the form.
            **kwargs: Keyword arguments forwarded to the form.

        Returns:
            Any: A form instance.
        """
        return self._list_form_class(*args, **kwargs)

    def get_save_return_url(self, model: Any, is_created: bool = False) -> str:
        """Return the URL the user is redirected to after a successful save.

        Args:
            model: Saved object.
            is_created: Whether the object was newly created.

        Returns:
            str: A redirect URL.

        Example:
            ```python
            class MyModelView(ModelView):
                def get_save_return_url(self, model, is_created):
                    return self.get_url('.details_view', id=model.id)
            ```
        """
        return (
            self.get_url(".details_view", id=model.id)
            if hasattr(self, "get_url")
            else "#"
        )
