from wtforms.fields import HiddenField
from wtforms.fields.core import UnboundField
from wtforms.validators import InputRequired
from ...template.forms.widgets import XEditableWidget


class FormMixin:
    """Form mixin for model view."""

    def create_editable_list_form(self, form_class, widget=None):
        """
        Create a form class with all the fields wrapped in a FieldList.

        Wrapping each field in FieldList allows submitting POST requests
        in this format: ('<field_name>-<primary_key>', '<value>')

        Used in the editable list view.

        :param form_base_class:
            WTForms form class, by default `form_base_class` from base.
        :param form_class:
            WTForms form class generated by `form.get_form`.
        :param widget:
            WTForms widget class. Defaults to `XEditableWidget`.
        """
        if widget is None:
            widget = XEditableWidget()

        class ListForm(self.form_base_class):
            list_form_pk = HiddenField(validators=[InputRequired()])

        for name, obj in form_class.__dict__.items():
            if not name.startswith("_") and isinstance(obj, UnboundField):
                if name == "list_form_pk":
                    raise Exception("Form already has a list_form_pk column.")
                obj.kwargs["widget"] = widget
                setattr(ListForm, name, obj)

        return ListForm
